### PR TITLE
Add `mock` to root aggregate

### PR DESCRIPTION
**Pull request by armanbilge**

### CODE REVIEW

**Comment by armanbilge** [comment]
Did the bare minimum to fix compile, but still need to actually integrate the new APIs.

**Comment by daddykotex** [comment]
Ahh my open source creds! Im happy to look into it. It will help me wrap my head around natchez

**Review by daddykotex — APPROVED** [review]

**Comment by daddykotex** [comment]
Can we get that merged and released or do you prefer to have: `actually integrate the new APIs` before we proceed?

**Comment by armanbilge** [comment]
Oh maybe I misunderstood, I thought you had volunteered to look into that? 😅

**Comment by daddykotex** [comment]
> Oh maybe I misunderstood, I thought you had volunteered to look into that? 

Yeah, I will. I was just thinking you'd cut a release just to have all artifacts at 3+, then I could come around with proper usage of the new apis. But it's fine, I will come up with a PR as fast as I can

**Comment by daddykotex** [comment]
Opened https://github.com/armanbilge/natchez/pull/1 on your branch

**Comment by daddykotex** [comment]
superseeded by https://github.com/tpolecat/natchez/pull/712

**Pull request merged**
