### PR TITLE
Add an example of Trace instance for IO

### PR DESCRIPTION
**Pull request by mwz**
Hello, this PR adds a simple `Trace[IO]` example to the docs.
Would that be sufficient, or should I expand this to cover anything else?

### CODE REVIEW

**Comment by kubukoz** [comment]
I think the docs should use `Trace.ioTraceForEntryPoint`, it's more convenient.

It looks sufficient to me but I'd make that change^ :)

**Comment by kubukoz** [comment]
sorry, I see I wasn't clear: I think the EntryPoint way should be the official recommendation, so it should go first. Is that OK with you?

**Comment by mwz** [comment]
Sounds good—I've updated it 👍🏻

**Review by kubukoz — APPROVED** [review]

**Comment by mwz** [comment]
@kubukoz, how do we get the website deployed?
Do I need to manually pr the generated static content against the `gh-pages` branch? It looks like it hasn't been updated in 3 years 🙀

**Comment by kubukoz** [comment]
uh yeah I think we don't have any automation for the site. I'd rather we add a step that publishes to gh-pages as part of CI, using sbt-typelevel's github actions codegen; but regardless we should see if the build still works locally in the first place.

**Comment by mwz** [comment]
ok no worries - I'm happy to look into that

**Pull request merged**
